---
name: CI

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase.
        uses: actions/checkout@v3

      - name: Install pnpm and dependencies.
        uses: pnpm/action-setup@v2
        with:
          version: 7.13.2
          run_install: |
            - recursive: true

      - name: Lint codebase.
        run: pnpm lint
